language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: master



# language: node_js
# node_js:
#   - "stable"
# cache: 
#     directories:
#   - node_modules
# before_script :
#  - curl -o- -L https://yarnpkg.com/install.sh | bash -s
#  - export PATH=$HOME/.yarn/bin:$PATH
#  - yarn install
# script:
#  - npm run build
# deploy:
#   provider: gh-pages
#   local_dir: build
#   on:
#     branch: master
#   skip_cleanup: true
#   github_token: $GITHUB_TOKEN