language: node_js
node_js:
 - 12.19.0
cache: yarn

install:
 - yarn install

script:
  - yarn test
  - yarn run build

deploy:
 provider: pages
 skip-cleanup: true
 github-tocken: $GITHUB_TOKEN
 on:
  branch: master